---
title: "occupancy heatmap"
output: html_notebook
---

```{r}
library(tidyverse)
library(leaflet)
```

```{r}
hospital_location_occupancy <- read_csv("data/cleaned_data/hospital_location_occupancy.csv")
occupancy_per_hb <- read_csv("data/cleaned_data/occupancy_per_hb.csv") %>% 
  mutate(quarter = zoo::as.yearqtr(quarter))
```

```{r}
hospital_location_occupancy
```

```{r}
hospital_location_occupancy %>% 
  ggplot() +
  aes(x = percentage_occupancy, y = location) +
  geom_col()
```
```{r}
hospital_location_occupancy %>% 
  summarise(count = n(), .by = location) %>% 
  arrange(desc(count))
```
```{r}
hospital_location_occupancy %>% 
  filter(location == "A101H")
```


```{r}
occupancy_pal <- colorNumeric(
  palette = "viridis",
  domain = hospital_location_occupancy$percentage_occupancy)

hospital_location_occupancy %>% 
      #filter(hb == "S08000031") %>% 
      leaflet() %>% 
      addProviderTiles(providers$Stamen.TonerLite) %>% 
      addCircleMarkers(lng = ~ longitude,
                       lat = ~ latitude,
                       weight = 1,
                       radius = 5,
                       fillOpacity = 1,
                       popup = ~ paste(location_name, br(), "Board:", hb),
                       color = ~occupancy_pal(percentage_occupancy)
      )
```

