---
title: "R Notebook"
output: html_notebook
---

```{r}
# open libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
```


```{r}
waiting_times <- read.csv("../data/a_and_e/monthly_ae_activity_202305.csv") %>% 
                clean_names()

```

```{r}
# open libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
```

```{r}

season_name <- setNames(rep(c("winter", "spring", "summer", "autumn"), each = 3),
                        month.name)

attendances_ae <- waiting_times %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  #let's add a column indicating season
  mutate(month_label = month(
                      ym(month), label = TRUE, abbr = FALSE), 
         .before = hbt) %>% 
  mutate(season = season_name[month_label], .before = hbt) %>% 
  # create a  year column, 
  mutate(year = year(ym(month)), .before = hbt) %>% 
  # create a "fake" year for december, to make sure that december of previous year falls in next year for correct grouping
  mutate(year = if_else(month_label == "December", year+1, year)) %>% 
  mutate(season = if_else(month_label == "December", "winter", season)) %>%  
  mutate(season = if_else(month_label == "March", "spring", season)) %>% 
  mutate(season = if_else(month_label == "June", "summer", season)) %>% 
  mutate(season = if_else(month_label == "September", "autumn", season)) %>% 
  # create a column to later filter right season!
  mutate(right_season = if_else(
                        str_detect(season, "winter|summer"), TRUE, FALSE),
         .before = hbt) 
```

```{r}
attendances_ae %>% 
  distinct(hbt)
```


```{r}
# Do statistical test
# create variables
test_summer <- attendances_ae %>% 
  filter(year < 2020 & year > 2007) %>% 
  filter(hbt == "S08000030") %>% 
  filter(season == "summer") %>% 
  group_by(season, year) %>% 
  summarise(total_attendances = sum(number_of_attendances_all)) %>%
  ungroup() %>% 
  select(total_attendances)

test_winter <- attendances_ae %>% 
  filter(year < 2020 & year > 2007) %>% 
  filter(hbt == "S08000030") %>% 
  filter(season == "winter") %>% 
  group_by(season, year) %>% 
  summarise(total_attendances = sum(number_of_attendances_all)) %>%
  ungroup() %>% 
  select(total_attendances)

# do final hypothesis test
t.test(test_summer$total_attendances,
       test_winter$total_attendances,
       alternative = "two.sided",
       paired = FALSE,
       conf.level = 0.95)
```

```{r}
waiting_times %>% 
  select(month, hbt, number_of_attendances_all) %>%
  group_by(month) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  ggplot() +
  aes(x = ym(month), y = total_number_attendances_all) +
  geom_line(colour = "#253494") +
  labs(
        title = "Total attendances at A&E departments in Scotland",
        x = "\nYear",
        y = "Total attendances\n"
      ) +
  theme(legend.position = "bottom",
            panel.background = element_blank(),
            panel.grid.minor.x = element_blank(),
            panel.grid.minor.y = element_blank(),
            axis.text = element_text(size = 12),
            axis.title = element_text(size = 16),
            legend.title = element_text(size = 12),
            plot.title = element_text(size = 20)) 
  ggsave("total_attendances.pdf")



                 
```

