---
title: "R Notebook"
output: html_notebook
---
Goal: looking at waiting times at A&E
1. NumberofattendancesAll
2. Numberwithin 4 hours
3. Number over 4 hours
```{r}
waiting_times <- read.csv("../data/a_and_e/monthly_ae_activity_202305.csv")

```

```{r}
# open libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
```

```{r}
waiting_times_1 <- clean_names(waiting_times)
```

```{r}
#explore data
head(waiting_times_1)
glimpse(waiting_times)
view(waiting_times_1)
colnames(waiting_times_1)
```

```{r}
waiting_times_1 %>% 
  distinct(country)
# only a single country = Scotland

waiting_times_1 %>% 
  distinct(department_type)
# 2 departments only, injury and emergency (=A&E)


waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  mutate(month_new = ym(month)) %>% 
  group_by(hbt) %>% 
  ggplot() +
  aes(x = month_new, group = hbt) +
  geom_histogram((aes(fill = hbt))
  
#group by hbt, and/or location, and/or department
```  
  
```{r}
# line graph for total attendances in A&E
 waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>%
  group_by(month) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  ggplot() +
  aes(x = ym(month), y = total_number_attendances_all) +
  geom_line()
```

```{r}
# Goal: lets check seasonality in waiting time data: 
# compare July and January for each year to start

waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  # filter for at end 01 (january) and at end 07 (july)
  mutate(right_month = if_else(
                        str_detect(month, "01$|07$"), TRUE, FALSE), .before = hbt) %>% 
  filter(right_month == TRUE) %>%
  group_by(month, hbt) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  mutate(year = str_sub(month, start = 1, end = 4), .after = month) %>% 
  ggplot() +
  aes(x = ym(month), y = total_number_attendances_all, group = hbt) +
    geom_col(aes(fill = hbt), position = "dodge") +
  facet_wrap(~ hbt, scales = "free")
  
```
```{r}
# so we see a difference between january and july for each year across the HB's
# let's calculate significance

#first create the sample datasets you want to compare (january vs july)
test_january <- 
waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  # filter for at end 01 (january) and at end 07 (july)
  mutate(right_month = if_else(
                        str_detect(month, "01$|07$"), TRUE, FALSE), .before = hbt) %>% 
  filter(right_month == TRUE) %>%
  group_by(month, hbt) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  mutate(year = str_sub(month, start = 1, end = 4), .after = month) %>% 
  mutate(month_nr = str_sub(month, start = 5, end = 6), .after = month) %>% 
  filter(month_nr == "01") %>% 
  filter(year < 2020) %>% 
  ungroup() %>% 
  select(total_number_attendances_all)

test_july <- 
waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  # filter for at end 01 (january) and at end 07 (july)
  mutate(right_month = if_else(
                        str_detect(month, "01$|07$"), TRUE, FALSE), .before = hbt) %>% 
  filter(right_month == TRUE) %>%
  group_by(month, hbt) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  mutate(year = str_sub(month, start = 1, end = 4), .after = month) %>% 
  mutate(month_nr = str_sub(month, start = 5, end = 6), .after = month) %>% 
  filter(month_nr == "07") %>% 
  filter(year < 2020) %>% 
  ungroup() %>% 
  select(total_number_attendances_all)
  
# now run the actual test
t.test(test_january$total_number_attendances_all,
       test_july$total_number_attendances_all,
       alternative = "two.sided",
       paired = FALSE,
       conf.level = 0.95)

```
```{r}
# let's do the same as above but than for one HB that seem to show an extreme summer/winter dif

test_january_HB28 <- 
waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  # filter for at end 01 (january) and at end 07 (july)
  mutate(right_month = if_else(
                        str_detect(month, "01$|07$"), TRUE, FALSE), .before = hbt) %>% 
  filter(right_month == TRUE) %>%
  group_by(month, hbt) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  mutate(year = str_sub(month, start = 1, end = 4), .after = month) %>% 
  mutate(month_nr = str_sub(month, start = 5, end = 6), .after = month) %>% 
  filter(month_nr == "01") %>% 
  filter(year < 2020) %>% 
  filter(hbt == "S08000028") %>% 
  ungroup() %>% 
  select(total_number_attendances_all)

test_july_HB28 <- 
waiting_times_1 %>% 
  select(month, hbt, number_of_attendances_all) %>% 
  # filter for at end 01 (january) and at end 07 (july)
  mutate(right_month = if_else(
                        str_detect(month, "01$|07$"), TRUE, FALSE), .before = hbt) %>% 
  filter(right_month == TRUE) %>%
  group_by(month, hbt) %>% 
  summarise(total_number_attendances_all = sum(number_of_attendances_all)) %>% 
  mutate(year = str_sub(month, start = 1, end = 4), .after = month) %>% 
  mutate(month_nr = str_sub(month, start = 5, end = 6), .after = month) %>% 
  filter(month_nr == "07") %>% 
  filter(year < 2020) %>% 
  filter(hbt == "S08000028") %>% 
  ungroup() %>% 
  select(total_number_attendances_all)
  
# now run the actual test
t.test(test_january_HB28$total_number_attendances_all,
       test_july_HB28$total_number_attendances_all,
       alternative = "two.sided",
       paired = FALSE,
       conf.level = 0.95)
```




```{r}
# create a line for waiting times less than 4 hours and over 4 hours

waiting_times_1 %>% 
  select(month, hbt, number_within4hours_all, number_over4hours_all) %>%
  group_by(month) %>% 
  summarise(total_number_within4hrs = sum(number_within4hours_all),
            total_number_over4hrs = sum(number_over4hours_all)) %>% 
  ggplot() +
  aes(x = ym(month)) +
  geom_line(aes(y = total_number_within4hrs), colour = "indianred") +
  geom_line(aes(y = total_number_over4hrs), colour = "springgreen4")



```



