---
title: "R Notebook"
output: html_notebook
---

```{r}
# open libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
```

```{r}
demo_attendances <- read.csv("../data/a_and_e/opendata_monthly_ae_demographics_202305.csv") %>% 
  clean_names()
```

```{r}
view(demo_attendances)
```

```{r}
# lets add some additional columns with seasonality

#1. create variable for season
season_name <- setNames(rep(c("winter", "spring", "summer", "autumn"), each = 3),
                        month.name)

# 2. create table specifying season
demo_attendances_season <- demo_attendances %>% 
  select(month, hbt, age, sex, deprivation, number_of_attendances) %>% 
  #let's add a column indicating season
  mutate(month_label = month(
                      ym(month), label = TRUE, abbr = FALSE), 
         .before = hbt) %>% 
  mutate(season = season_name[month_label], .before = hbt) %>% 
  # create a  year column, 
  mutate(year = year(ym(month)), .before = hbt) %>% 
  # create a "fake" year for december, to make sure that december of previous year falls in next year for correct grouping
  mutate(year = if_else(month_label == "December", year+1, year)) %>% 
  mutate(season = if_else(month_label == "December", "winter", season)) %>%  
  mutate(season = if_else(month_label == "March", "spring", season)) %>% 
  mutate(season = if_else(month_label == "June", "summer", season)) %>% 
  mutate(season = if_else(month_label == "September", "autumn", season)) %>% 
  # create a column to later filter right season!
  mutate(right_season = if_else(
                        str_detect(season, "winter|summer"), TRUE, FALSE),
         .before = hbt) 

# 3. 
## deprivation
demo_attendances_season %>% 
  filter(right_season == TRUE) %>% 
  filter(year < 2020 & year > 2007) %>% 
  filter(hbt == "S08000028") %>% 
  select(year, season, hbt, deprivation, number_of_attendances) %>% 
  group_by(year, season, hbt, deprivation) %>% 
  summarise(total_per_deprivation = sum(number_of_attendances)) %>% 
  ggplot() +
  aes(x = year, y = total_per_deprivation, fill = as.character(deprivation), group = season) +
  geom_col(position = "dodge", col = "white")

  
## age
demo_attendances_season %>% 
  filter(right_season == TRUE) %>% 
  filter(year < 2020 & year > 2007) %>% 
  filter(hbt == "S08000028") %>% 
  select(year, season, hbt, age, number_of_attendances) %>% 
  group_by(year, season, hbt, age) %>% 
  summarise(total_per_age = sum(number_of_attendances)) %>% 
  ggplot() +
  aes(x = year, y = total_per_age, fill = as.character(age), group = season) +
  geom_col(position = "dodge", col = "white") 
  
## sex
demo_attendances_season %>% 
  filter(right_season == TRUE) %>% 
  filter(year < 2020 & year > 2007) %>% 
  filter(hbt == "S08000028") %>% 
  select(year, season, hbt, sex, number_of_attendances) %>% 
  group_by(year, season, hbt, sex) %>% 
  summarise(total_per_sex = sum(number_of_attendances)) %>% 
  ggplot() +
  aes(x = year, y = total_per_sex, fill = as.character(sex), group = season) +
  geom_col(position = "dodge", col = "white")
  

```

